//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonSkills
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int ID { get; set; }
        public Nullable<int> ID_Sponsor { get; set; }
        public string NameCard { get; set; }
        public string NumCard { get; set; }
        public string TimeEnd { get; set; }
        public string CVC { get; set; }
    
        public virtual SponsorRunner SponsorRunner { get; set; }
    }
}
