//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonSkills
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatisticsMarathon
    {
        public int ID { get; set; }
        public Nullable<int> ID_Marathon { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<System.DateTime> GeneralTime { get; set; }
        public Nullable<int> MyPlace { get; set; }
    
        public virtual Marathon Marathon { get; set; }
        public virtual User User { get; set; }
    }
}
