//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonSkills
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.StatisticsMarathon = new HashSet<StatisticsMarathon>();
        }
    
        public int ID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Gender { get; set; }
        public byte[] Photo { get; set; }
        public string Role { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> ID_Marathon { get; set; }
        public Nullable<int> ID_Inventory { get; set; }
        public Nullable<int> ID_Fund { get; set; }
        public string Country { get; set; }
        public Nullable<int> Payment { get; set; }
    
        public virtual Fund Fund { get; set; }
        public virtual Inventory Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatisticsMarathon> StatisticsMarathon { get; set; }
    }
}
